openapi: 3.0.0
info:
  title: HR Users API
  version: 1.0.0
  description: API for managing HR user records stored in an Excel file
servers:
  - url: https://openapismain.onrender.com
    description: Public deployment for HR agent integration
paths:
  /users:
    get:
      summary: Retrieve all HR user records
      operationId: getUsers
      responses:
        '200':
          description: List of HR users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    num:
                      type: integer
                      description: Unique employee ID
                    Name:
                      type: string
                      description: Full name of the employee
                    Job:
                      type: string
                      description: Job title or role
                    Address:
                      type: string
                      description: Employee address
                    RequestedTimeOff:
                      type: integer
                      description: Days of time off requested
    post:
      summary: Add a new HR user record
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - num
                - Name
                - Job
                - Address
                - RequestedTimeOff
              properties:
                num:
                  type: integer
                Name:
                  type: string
                Job:
                  type: string
                Address:
                  type: string
                RequestedTimeOff:
                  type: integer
      responses:
        '200':
          description: Confirmation of user addition
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      num:
                        type: integer
                      Name:
                        type: string
                      Job:
                        type: string
                      Address:
                        type: string
                      RequestedTimeOff:
                        type: integer
